export const collectionConstants = {
  USER_COLLECTION_REQUEST: 'USER_COLLECTION_REQUEST',
  USER_COLLECTION_SUCCESS: 'USER_COLLECTION_SUCCESS',
  USER_COLLECTION_FAILURE: 'USER_COLLECTION_FAILURE',
  COLLECTION_REQUEST: 'COLLECTION_REQUEST',
  COLLECTION_SUCCESS: 'COLLECTION_SUCCESS',
  COLLECTION_FAILURE: 'COLLECTION_FAILURE',
  CREATE_CARDS_REQUEST: 'CREATE_CARDS_REQUEST',
  CREATE_CARDS_SUCCESS: 'CREATE_CARDS_SUCCESS',
  CREATE_CARDS_FAILURE: 'CREATE_CARDS_FAILURE',
  CREATE_COLLECTION_REQUEST: 'CREATE_COLLECTION_REQUEST',
  CREATE_COLLECTION_SUCCESS: 'CREATE_COLLECTION_SUCCESS',
  CREATE_COLLECTION_FAILURE: 'CREATE_COLLECTION_FAILURE',
}